# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI="7"

inherit java-pkg-2

MY_PV=$(ver_rs 3 '-')

DESCRIPTION="Command-line clients for Virtual Organization Membership Service (VOMS)"
HOMEPAGE="https://italiangrid.github.io/voms"
SRC_URI="https://github.com/italiangrid/${PN}/archive/v${MY_PV}.tar.gz -> ${P}.tar.gz"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="doc"

DEPEND=">=virtual/jdk-1.8:*
	dev-java/commons-cli:1
	dev-java/commons-io:1
	dev-java/bcpkix:1.52"
BDEPEND="dev-java/maven-bin"
RDEPEND="${DEPEND}
	sci-physics/egi-igtf
	sci-physics/wlcg-voms"

S="${WORKDIR}/${PN}-${MY_PV}"

# Even though some of this stuff will not be used at runtime, it is all
# required in order to satisfy the maven build system.
EMAVEN_VENDOR=(
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-javadoc-plugin/2.9.1/maven-javadoc-plugin-2.9.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-plugins/24/maven-plugins-24.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/23/maven-parent-23.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/13/apache-13.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-javadoc-plugin/2.9.1/maven-javadoc-plugin-2.9.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-source-plugin/2.2.1/maven-source-plugin-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-plugins/23/maven-plugins-23.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/22/maven-parent-22.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/11/apache-11.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-source-plugin/2.2.1/maven-source-plugin-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/surefire/2.12.4/surefire-2.12.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-jar-plugin/2.5/maven-jar-plugin-2.5.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-plugins/25/maven-plugins-25.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/24/maven-parent-24.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/14/apache-14.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-jar-plugin/2.5/maven-jar-plugin-2.5.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-assembly-plugin/2.4.1/maven-assembly-plugin-2.4.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-assembly-plugin/2.4.1/maven-assembly-plugin-2.4.1.jar"
	"https://repo.maven.apache.org/maven2 junit/junit/4.10/junit-4.10.pom"
	"https://repo.maven.apache.org/maven2 org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.pom"
	"https://repo.maven.apache.org/maven2 org/hamcrest/hamcrest-parent/1.1/hamcrest-parent-1.1.pom"
	"https://repo.maven.apache.org/maven2 commons-cli/commons-cli/1.2/commons-cli-1.2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/11/commons-parent-11.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/4/apache-4.pom"
	"https://repo.maven.apache.org/maven2 commons-io/commons-io/2.0.1/commons-io-2.0.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/15/commons-parent-15.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/7/apache-7.pom"
	"https://repo.maven.apache.org/maven2 org/italiangrid/voms-api-java/3.3.0/voms-api-java-3.3.0.pom"
	"https://repo.maven.apache.org/maven2 eu/eu-emi/security/canl/2.5.0/canl-2.5.0.pom"
	"https://repo.maven.apache.org/maven2 org/bouncycastle/bcpkix-jdk15on/1.56/bcpkix-jdk15on-1.56.pom"
	"https://repo.maven.apache.org/maven2 org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.pom"
	"https://repo.maven.apache.org/maven2 commons-io/commons-io/2.4/commons-io-2.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/25/commons-parent-25.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/9/apache-9.pom"
	"https://repo.maven.apache.org/maven2 org/bouncycastle/bcpkix-jdk15on/1.58/bcpkix-jdk15on-1.58.pom"
	"https://repo.maven.apache.org/maven2 org/bouncycastle/bcprov-jdk15on/1.58/bcprov-jdk15on-1.58.pom"
	"https://repo.maven.apache.org/maven2 junit/junit/4.10/junit-4.10.jar"
	"https://repo.maven.apache.org/maven2 commons-cli/commons-cli/1.2/commons-cli-1.2.jar"
	"https://repo.maven.apache.org/maven2 org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar"
	"https://repo.maven.apache.org/maven2 commons-io/commons-io/2.0.1/commons-io-2.0.1.jar"
	"https://repo.maven.apache.org/maven2 eu/eu-emi/security/canl/2.5.0/canl-2.5.0.jar"
	"https://repo.maven.apache.org/maven2 org/italiangrid/voms-api-java/3.3.0/voms-api-java-3.3.0.jar"
	"https://repo.maven.apache.org/maven2 org/bouncycastle/bcpkix-jdk15on/1.58/bcpkix-jdk15on-1.58.jar"
	"https://repo.maven.apache.org/maven2 org/bouncycastle/bcprov-jdk15on/1.58/bcprov-jdk15on-1.58.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-api/2.0.6/maven-plugin-api-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven/2.0.6/maven-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/5/maven-parent-5.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/3/apache-3.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-project/2.0.6/maven-project-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-settings/2.0.6/maven-settings-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model/2.0.6/maven-model-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.4.1/plexus-utils-1.4.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/1.0.11/plexus-1.0.11.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-container-default/1.0-alpha-9-stable-1/plexus-container-default-1.0-alpha-9-stable-1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-containers/1.0.3/plexus-containers-1.0.3.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/1.0.4/plexus-1.0.4.pom"
	"https://repo.maven.apache.org/maven2 junit/junit/3.8.1/junit-3.8.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.0.4/plexus-utils-1.0.4.pom"
	"https://repo.maven.apache.org/maven2 classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-profile/2.0.6/maven-profile-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact-manager/2.0.6/maven-artifact-manager-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-repository-metadata/2.0.6/maven-repository-metadata-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/2.0.6/maven-artifact-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-registry/2.0.6/maven-plugin-registry-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-core/2.0.6/maven-core-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-parameter-documenter/2.0.6/maven-plugin-parameter-documenter-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting-api/2.0.6/maven-reporting-api-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting/2.0.6/maven-reporting-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia/1.0-alpha-7/doxia-1.0-alpha-7.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-error-diagnostics/2.0.6/maven-error-diagnostics-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 commons-cli/commons-cli/1.0/commons-cli-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-descriptor/2.0.6/maven-plugin-descriptor-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-monitor/2.0.6/maven-monitor-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 classworlds/classworlds/1.1/classworlds-1.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/2.0.6/plexus-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-filtering/1.1/maven-filtering-1.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/17/maven-shared-components-17.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/21/maven-parent-21.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/10/apache-10.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/2.0.2/plexus-2.0.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.12/plexus-interpolation-1.12.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-components/1.1.14/plexus-components-1.1.14.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/spice/spice-parent/10/spice-parent-10.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/forge/forge-parent/3/forge-parent-3.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-components/1.1.15/plexus-components-1.1.15.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/2.0.3/plexus-2.0.3.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-api/2.0.6/maven-plugin-api-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-registry/2.0.6/maven-plugin-registry-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact-manager/2.0.6/maven-artifact-manager-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-profile/2.0.6/maven-profile-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-core/2.0.6/maven-core-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-project/2.0.6/maven-project-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-parameter-documenter/2.0.6/maven-plugin-parameter-documenter-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting-api/2.0.6/maven-reporting-api-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-error-diagnostics/2.0.6/maven-error-diagnostics-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 commons-cli/commons-cli/1.0/commons-cli-1.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-repository-metadata/2.0.6/maven-repository-metadata-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-descriptor/2.0.6/maven-plugin-descriptor-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 classworlds/classworlds/1.1/classworlds-1.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model/2.0.6/maven-model-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-settings/2.0.6/maven-settings-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-monitor/2.0.6/maven-monitor-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/2.0.6/maven-artifact-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 junit/junit/3.8.1/junit-3.8.1.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-container-default/1.0-alpha-9-stable-1/plexus-container-default-1.0-alpha-9-stable-1.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-filtering/1.1/maven-filtering-1.1.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.jar"
	"https://repo.maven.apache.org/maven2 org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-api/2.0.9/maven-plugin-api-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven/2.0.9/maven-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/8/maven-parent-8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/2.0.9/maven-artifact-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.5.1/plexus-utils-1.5.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-core/2.0.9/maven-core-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-settings/2.0.9/maven-settings-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model/2.0.9/maven-model-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-parameter-documenter/2.0.9/maven-plugin-parameter-documenter-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-profile/2.0.9/maven-profile-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-repository-metadata/2.0.9/maven-repository-metadata-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-error-diagnostics/2.0.9/maven-error-diagnostics-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-project/2.0.9/maven-project-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact-manager/2.0.9/maven-artifact-manager-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-registry/2.0.9/maven-plugin-registry-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-descriptor/2.0.9/maven-plugin-descriptor-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-monitor/2.0.9/maven-monitor-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-toolchain/1.0/maven-toolchain-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-utils/0.1/maven-shared-utils-0.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/18/maven-shared-components-18.pom"
	"https://repo.maven.apache.org/maven2 com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/19/maven-shared-components-19.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-api/2.2.1/maven-plugin-api-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven/2.2.1/maven-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/11/maven-parent-11.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/5/apache-5.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-core/2.2.1/maven-core-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-settings/2.2.1/maven-settings-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model/2.2.1/maven-model-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-parameter-documenter/2.2.1/maven-plugin-parameter-documenter-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.pom"
	"https://repo.maven.apache.org/maven2 org/slf4j/slf4j-parent/1.5.6/slf4j-parent-1.5.6.pom"
	"https://repo.maven.apache.org/maven2 org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.pom"
	"https://repo.maven.apache.org/maven2 org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-profile/2.2.1/maven-profile-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/2.2.1/maven-artifact-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-repository-metadata/2.2.1/maven-repository-metadata-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-error-diagnostics/2.2.1/maven-error-diagnostics-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-project/2.2.1/maven-project-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact-manager/2.2.1/maven-artifact-manager-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-registry/2.2.1/maven-plugin-registry-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-descriptor/2.2.1/maven-plugin-descriptor-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-monitor/2.2.1/maven-monitor-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/spice/spice-parent/12/spice-parent-12.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/forge/forge-parent/4/forge-parent-4.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.5.5/plexus-utils-1.5.5.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-containers/1.5.5/plexus-containers-1.5.5.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/2.0.7/plexus-2.0.7.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-compiler-api/2.2/plexus-compiler-api-2.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-compiler/2.2/plexus-compiler-2.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-components/1.3.1/plexus-components-1.3.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/3.3.1/plexus-3.3.1.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/spice/spice-parent/17/spice-parent-17.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/forge/forge-parent/10/forge-parent-10.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/3.2/plexus-3.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-compiler-manager/2.2/plexus-compiler-manager-2.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-compiler-javac/2.2/plexus-compiler-javac-2.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-compilers/2.2/plexus-compilers-2.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-container-default/1.5.5/plexus-container-default-1.5.5.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.4.5/plexus-utils-1.4.5.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-classworlds/2.2.2/plexus-classworlds-2.2.2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/xbean/xbean/3.4/xbean-3.4.pom"
	"https://repo.maven.apache.org/maven2 log4j/log4j/1.2.12/log4j-1.2.12.pom"
	"https://repo.maven.apache.org/maven2 commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.pom"
	"https://repo.maven.apache.org/maven2 com/google/collections/google-collections/1.0/google-collections-1.0.pom"
	"https://repo.maven.apache.org/maven2 com/google/google/1/google-1.pom"
	"https://repo.maven.apache.org/maven2 junit/junit/3.8.2/junit-3.8.2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-settings/2.0.9/maven-settings-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/2.0.9/maven-artifact-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-api/2.0.9/maven-plugin-api-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-parameter-documenter/2.0.9/maven-plugin-parameter-documenter-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-profile/2.0.9/maven-profile-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-repository-metadata/2.0.9/maven-repository-metadata-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.5.1/plexus-utils-1.5.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-error-diagnostics/2.0.9/maven-error-diagnostics-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-core/2.0.9/maven-core-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model/2.0.9/maven-model-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-registry/2.0.9/maven-plugin-registry-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-descriptor/2.0.9/maven-plugin-descriptor-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-monitor/2.0.9/maven-monitor-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-project/2.0.9/maven-project-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact-manager/2.0.9/maven-artifact-manager-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-toolchain/1.0/maven-toolchain-1.0.jar"
	"https://repo.maven.apache.org/maven2 com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-utils/0.1/maven-shared-utils-0.1.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-compiler-manager/2.2/plexus-compiler-manager-2.2.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-compiler-api/2.2/plexus-compiler-api-2.2.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-compiler-javac/2.2/plexus-compiler-javac-2.2.jar"
	"https://repo.maven.apache.org/maven2 org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-classworlds/2.2.2/plexus-classworlds-2.2.2.jar"
	"https://repo.maven.apache.org/maven2 commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar"
	"https://repo.maven.apache.org/maven2 junit/junit/3.8.2/junit-3.8.2.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-container-default/1.5.5/plexus-container-default-1.5.5.jar"
	"https://repo.maven.apache.org/maven2 log4j/log4j/1.2.12/log4j-1.2.12.jar"
	"https://repo.maven.apache.org/maven2 com/google/collections/google-collections/1.0/google-collections-1.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/surefire-booter/2.12.4/surefire-booter-2.12.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/surefire-api/2.12.4/surefire-api-2.12.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/maven-surefire-common/2.12.4/maven-surefire-common-2.12.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugin-tools/maven-plugin-annotations/3.1/maven-plugin-annotations-3.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugin-tools/maven-plugin-tools/3.1/maven-plugin-tools-3.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting-api/2.0.9/maven-reporting-api-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting/2.0.9/maven-reporting-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-toolchain/2.0.9/maven-toolchain-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/22/commons-parent-22.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-common-artifact-filters/1.3/maven-common-artifact-filters-1.3.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/12/maven-shared-components-12.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/13/maven-parent-13.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/6/apache-6.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-container-default/1.0-alpha-9/plexus-container-default-1.0-alpha-9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-common-artifact-filters/1.3/maven-common-artifact-filters-1.3.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/surefire-api/2.12.4/surefire-api-2.12.4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/maven-surefire-common/2.12.4/maven-surefire-common-2.12.4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/surefire-booter/2.12.4/surefire-booter-2.12.4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting-api/2.0.9/maven-reporting-api-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-toolchain/2.0.9/maven-toolchain-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugin-tools/maven-plugin-annotations/3.1/maven-plugin-annotations-3.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/surefire-junit4/2.12.4/surefire-junit4-2.12.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/surefire-providers/2.12.4/surefire-providers-2.12.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/surefire-junit4/2.12.4/surefire-junit4-2.12.4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-archiver/2.1/plexus-archiver-2.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/spice/spice-parent/16/spice-parent-16.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/forge/forge-parent/5/forge-parent-5.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-io/2.0.2/plexus-io-2.0.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-components/1.1.19/plexus-components-1.1.19.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/3.0.1/plexus-3.0.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.15/plexus-interpolation-1.15.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0.15/plexus-utils-3.0.15.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-archiver/2.4.4/plexus-archiver-2.4.4.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-components/1.3/plexus-components-1.3.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/3.3/plexus-3.3.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-io/2.0.10/plexus-io-2.0.10.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-components/1.2/plexus-components-1.2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-compress/1.5/commons-compress-1.5.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/28/commons-parent-28.pom"
	"https://repo.maven.apache.org/maven2 org/tukaani/xz/1.2/xz-1.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.15/plexus-interpolation-1.15.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-io/2.0.10/plexus-io-2.0.10.jar"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-compress/1.5/commons-compress-1.5.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0.15/plexus-utils-3.0.15.jar"
	"https://repo.maven.apache.org/maven2 org/tukaani/xz/1.2/xz-1.2.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-archiver/2.4.4/plexus-archiver-2.4.4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting-api/2.2.1/maven-reporting-api-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting/2.2.1/maven-reporting-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia/1.1/doxia-1.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-container-default/1.0-alpha-30/plexus-container-default-1.0-alpha-30.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-containers/1.0-alpha-30/plexus-containers-1.0-alpha-30.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-classworlds/1.2-alpha-9/plexus-classworlds-1.2-alpha-9.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/1.0.10/plexus-1.0.10.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-common-artifact-filters/1.4/maven-common-artifact-filters-1.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/2.0.8/maven-artifact-2.0.8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven/2.0.8/maven-2.0.8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/6/maven-parent-6.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.4.6/plexus-utils-1.4.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model/2.0.8/maven-model-2.0.8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-project/2.0.8/maven-project-2.0.8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-settings/2.0.8/maven-settings-2.0.8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-profile/2.0.8/maven-profile-2.0.8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact-manager/2.0.8/maven-artifact-manager-2.0.8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-repository-metadata/2.0.8/maven-repository-metadata-2.0.8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-registry/2.0.8/maven-plugin-registry-2.0.8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-api/2.0.8/maven-plugin-api-2.0.8.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/2.1/plexus-utils-2.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.19/plexus-interpolation-1.19.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/file-management/1.1/file-management-1.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/4/maven-shared-components-4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/4/maven-parent-4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-api/2.0/maven-plugin-api-2.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven/2.0/maven-2.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-io/1.0/maven-shared-io-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/2.0.2/maven-artifact-2.0.2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven/2.0.2/maven-2.0.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact-manager/2.0.2/maven-artifact-manager-2.0.2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-repository-metadata/2.0.2/maven-repository-metadata-2.0.2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/wagon/wagon-provider-api/1.0-alpha-6/wagon-provider-api-1.0-alpha-6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/wagon/wagon/1.0-alpha-6/wagon-1.0-alpha-6.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.2/plexus-utils-1.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/1.0.5/plexus-1.0.5.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-io/1.1/maven-shared-io-1.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/8/maven-shared-components-8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/7/maven-parent-7.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-filtering/1.2/maven-filtering-1.2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-utils/0.3/maven-shared-utils-0.3.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-io/2.0.9/plexus-io-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0.10/plexus-utils-3.0.10.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-repository-builder/1.0-alpha-2/maven-repository-builder-1.0-alpha-2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/7/maven-shared-components-7.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/2.0.4/maven-artifact-2.0.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven/2.0.4/maven-2.0.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact-manager/2.0.4/maven-artifact-manager-2.0.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-repository-metadata/2.0.4/maven-repository-metadata-2.0.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-project/2.0.4/maven-project-2.0.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-settings/2.0.4/maven-settings-2.0.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model/2.0.4/maven-model-2.0.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-profile/2.0.4/maven-profile-2.0.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-common-artifact-filters/1.0-alpha-1/maven-common-artifact-filters-1.0-alpha-1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/6/maven-shared-components-6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-api/2.2.1/maven-plugin-api-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-parameter-documenter/2.2.1/maven-plugin-parameter-documenter-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-settings/2.2.1/maven-settings-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.jar"
	"https://repo.maven.apache.org/maven2 org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting-api/2.2.1/maven-reporting-api-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-profile/2.2.1/maven-profile-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-core/2.2.1/maven-core-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-repository-metadata/2.2.1/maven-repository-metadata-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-error-diagnostics/2.2.1/maven-error-diagnostics-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact-manager/2.2.1/maven-artifact-manager-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-descriptor/2.2.1/maven-plugin-descriptor-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-monitor/2.2.1/maven-monitor-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar"
	"https://repo.maven.apache.org/maven2 org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-registry/2.2.1/maven-plugin-registry-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/2.2.1/maven-artifact-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model/2.2.1/maven-model-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-common-artifact-filters/1.4/maven-common-artifact-filters-1.4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-project/2.2.1/maven-project-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/file-management/1.1/file-management-1.1.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.19/plexus-interpolation-1.19.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/wagon/wagon-provider-api/1.0-alpha-6/wagon-provider-api-1.0-alpha-6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-io/1.1/maven-shared-io-1.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-filtering/1.2/maven-filtering-1.2.jar"
	"https://repo.maven.apache.org/maven2 backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-repository-builder/1.0-alpha-2/maven-repository-builder-1.0-alpha-2.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-io/2.0.9/plexus-io-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-utils/0.3/maven-shared-utils-0.3.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-toolchain/2.2.1/maven-toolchain-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/15/maven-shared-components-15.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/16/maven-parent-16.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia/1.0/doxia-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/10/maven-parent-10.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-invoker/2.0.9/maven-invoker-2.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/9/maven-shared-components-9.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.5.6/plexus-utils-1.5.6.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/1.0.12/plexus-1.0.12.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.4.9/plexus-utils-1.4.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-site-renderer/1.0/doxia-site-renderer-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-sitetools/1.0/doxia-sitetools-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.5.7/plexus-utils-1.5.7.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-components/1.1.12/plexus-components-1.1.12.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-velocity/1.1.7/plexus-velocity-1.1.7.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-container-default/1.0-alpha-20/plexus-container-default-1.0-alpha-20.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-containers/1.0-alpha-20/plexus-containers-1.0-alpha-20.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.3/plexus-utils-1.3.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/1.0.8/plexus-1.0.8.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-classworlds/1.2-alpha-7/plexus-classworlds-1.2-alpha-7.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/1.0.9/plexus-1.0.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/velocity/velocity/1.5/velocity-1.5.pom"
	"https://repo.maven.apache.org/maven2 commons-collections/commons-collections/3.1/commons-collections-3.1.pom"
	"https://repo.maven.apache.org/maven2 commons-lang/commons-lang/2.1/commons-lang-2.1.pom"
	"https://repo.maven.apache.org/maven2 oro/oro/2.0.8/oro-2.0.8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-decoration-model/1.0/doxia-decoration-model-1.0.pom"
	"https://repo.maven.apache.org/maven2 commons-collections/commons-collections/3.2/commons-collections-3.2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-module-apt/1.0/doxia-module-apt-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-modules/1.0/doxia-modules-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-module-fml/1.0/doxia-module-fml-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-module-xdoc/1.0/doxia-module-xdoc-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-module-xhtml/1.0/doxia-module-xhtml-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/wagon/wagon-provider-api/1.0-beta-6/wagon-provider-api-1.0-beta-6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/wagon/wagon/1.0-beta-6/wagon-1.0-beta-6.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.4.2/plexus-utils-1.4.2.pom"
	"https://repo.maven.apache.org/maven2 commons-lang/commons-lang/2.4/commons-lang-2.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/9/commons-parent-9.pom"
	"https://repo.maven.apache.org/maven2 commons-io/commons-io/2.2/commons-io-2.2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/24/commons-parent-24.pom"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/httpclient/4.2.3/httpclient-4.2.3.pom"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/httpcomponents-client/4.2.3/httpcomponents-client-4.2.3.pom"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/project/6/project-6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/httpcore/4.2.2/httpcore-4.2.2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/httpcomponents-core/4.2.2/httpcomponents-core-4.2.2.pom"
	"https://repo.maven.apache.org/maven2 commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/5/commons-parent-5.pom"
	"https://repo.maven.apache.org/maven2 commons-codec/commons-codec/1.6/commons-codec-1.6.pom"
	"https://repo.maven.apache.org/maven2 log4j/log4j/1.2.14/log4j-1.2.14.pom"
	"https://repo.maven.apache.org/maven2 com/thoughtworks/qdox/qdox/1.12.1/qdox-1.12.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/codehaus-parent/4/codehaus-parent-4.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-archiver/2.1.2/plexus-archiver-2.1.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0.2/plexus-utils-3.0.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/3.1/plexus-3.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-io/2.0.4/plexus-io-2.0.4.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-invoker/2.0.9/maven-invoker-2.0.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-toolchain/2.2.1/maven-toolchain-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-velocity/1.1.7/plexus-velocity-1.1.7.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-site-renderer/1.0/doxia-site-renderer-1.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.jar"
	"https://repo.maven.apache.org/maven2 oro/oro/2.0.8/oro-2.0.8.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-decoration-model/1.0/doxia-decoration-model-1.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-module-apt/1.0/doxia-module-apt-1.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-module-fml/1.0/doxia-module-fml-1.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-module-xhtml/1.0/doxia-module-xhtml-1.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-module-xdoc/1.0/doxia-module-xdoc-1.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/wagon/wagon-provider-api/1.0-beta-6/wagon-provider-api-1.0-beta-6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/velocity/velocity/1.5/velocity-1.5.jar"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/httpclient/4.2.3/httpclient-4.2.3.jar"
	"https://repo.maven.apache.org/maven2 commons-collections/commons-collections/3.2/commons-collections-3.2.jar"
	"https://repo.maven.apache.org/maven2 commons-io/commons-io/2.2/commons-io-2.2.jar"
	"https://repo.maven.apache.org/maven2 commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar"
	"https://repo.maven.apache.org/maven2 commons-codec/commons-codec/1.6/commons-codec-1.6.jar"
	"https://repo.maven.apache.org/maven2 commons-lang/commons-lang/2.4/commons-lang-2.4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/httpcore/4.2.2/httpcore-4.2.2.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-container-default/1.0-alpha-9/plexus-container-default-1.0-alpha-9.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-archiver/2.1.2/plexus-archiver-2.1.2.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-io/2.0.4/plexus-io-2.0.4.jar"
	"https://repo.maven.apache.org/maven2 com/thoughtworks/qdox/qdox/1.12.1/qdox-1.12.1.jar"
	"https://repo.maven.apache.org/maven2 log4j/log4j/1.2.14/log4j-1.2.14.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-archiver/2.2/plexus-archiver-2.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-components/1.1.20/plexus-components-1.1.20.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0.7/plexus-utils-3.0.7.pom"
	"https://repo.maven.apache.org/maven2 classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-archiver/2.2/plexus-archiver-2.2.jar"
)

PATCHES=(
	"${FILESDIR}"/voms-clients-java-change-default-proxy-cert-key-length-to-2048-bits.patch
	"${FILESDIR}"/voms-clients-java-use-a-more-sensible-timeout.patch
)

__set_vendor_uri() {
	local lib
	for lib in "${EMAVEN_VENDOR[@]}"; do
		SRC_URI+=" ${lib%% *}/${lib##* }"
	done
}

__set_vendor_uri
unset -f __set_vendor_uri

src_prepare() {
	sed -e 's:</settings>:<localRepository>'${T}/m2'</localRepository></settings>:g' < \
		"${EPREFIX}/usr/share/$(readlink "${EPREFIX}/usr/bin/mvn" |
		sed 's:mvn:maven-bin:')/conf/settings.xml" > "${S}"/settings.xml || \
			die "failed to create settings.xml"
	default
}

src_unpack() {
	unpack "${P}.tar.gz"
	local d f maven_basedir="${T}/m2"
	mkdir -p "${maven_basedir}" || die
	for f in "${EMAVEN_VENDOR[@]}"; do
		f=${f##* }
		d=${f%/*}
		f=${f##*/}
		mkdir -p "${maven_basedir}"/"${d}" || die
		cp "${DISTDIR}/${f}" "${maven_basedir}/${d}/" || die
	done
}

src_compile() {
	default
	mvn -s "${S}"/settings.xml --offline \
		package || die
}

src_install() {
	java-pkg_getjars commons-cli-1,commons-io-1,bcpkix-1.52
	java-pkg_newjar target/${P}.jar ${PN}.jar
	java-pkg_newjar "${T}/m2/org/italiangrid/voms-api-java/${PV}/voms-api-java-${PV}.jar" voms-api-java.jar
	java-pkg_newjar "${T}/m2/eu/eu-emi/security/canl/2.5.0/canl-2.5.0.jar" canl.jar
	for tool in init info destroy; do
		java-pkg_dolauncher voms-proxy-${tool}3 --main org.italiangrid.voms.clients.VomsProxy${tool^} --java_args="-XX:+UseSerialGC -Xmx16m"
		#sed -i	-e "s/voms-proxy-${tool}/voms-proxy-${tool}3/g" \
		#	-e "s/VOMS-PROXY-${tool^^}/VOMS-PROXY-${tool^^}3/g" man/voms-proxy-${tool}.1 \
		#	man/voms-proxy-${tool}.1
		newman man/voms-proxy-${tool}.1 voms-proxy-${tool}3.1
	done
	doman man/*.5
	default
}
